src/api/urls.py
from django.urls import (
    include,
    re_path,
)

from rest_framework import routers

from api.views import (
    index,
    JuraBookViewSet,
)

router = routers.DefaultRouter()
router.register(r'jura', JuraBookViewSet)

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^', include(router.urls)),
]

src/core/urls.py
from django.conf import settings
from django.urls import (
    include,
    re_path,
)
import django.views.static
from django.contrib import admin
from django.views.generic import TemplateView


import allauth.urls as allauth_urls
import rest_framework.urls as rest_framework_urls

import submission.urls as submission_urls
import manager.urls as manager_urls
import review.urls as review_urls
import api.urls as api_urls
import author.urls as author_urls
import editor.urls as editor_urls
import onetasker.urls as onetasker_urls
import swiftsubmit.urls as swiftsubmit_urls
import editorialreview.urls as editorialreview_urls
import django_summernote.urls as django_summernote_urls

from .views import (
    accept_proposal,
    activate,
    add_proposal_reviewers,
    assign_proposal,
    change_review_due_date,
    contact,
    contract_manager,
    dashboard,
    decline_proposal,
    delete_file,
    email_general,
    email_primary_contact,
    email_users,
    email_users_proposal,
    get_all,
    get_all_users,
    get_authors,
    get_editors,
    get_messages,
    get_onetaskers,
    get_proposal_users,
    index,
    login,
    login_orcid,
    logout,
    new_message,
    oai,
    overview,
    overview_inprogress,
    page,
    permission_denied,
    proposal,
    ProposalReviewCompletionEmail,
    proposal_add_editors,
    proposal_assign_edit,
    proposal_assign_user,
    proposal_assign_view,
    proposal_history,
    proposal_overview,
    proposal_review_declined,
    proposal_review_submitted,
    register,
    remove_proposal_review,
    reopen_proposal_review,
    RequestedReviewerDecisionEmail,
    request_proposal_revisions,
    reset_password,
    serve_all_files,
    serve_all_review_files,
    serve_all_review_files_one_click,
    serve_email_file,
    serve_file,
    serve_file_one_click,
    serve_marc21_file,
    serve_proposal_file_id,
    serve_versioned_file,
    start_proposal_review,
    switch_account,
    switch_account_user,
    task_complete,
    task_new,
    unauth_reset,
    unauth_reset_code,
    unauth_reset_password,
    update_file,
    update_profile,
    upload_additional,
    upload_manuscript,
    upload_misc_file,
    user_proposal,
    user_submission,
    versions_file,
    view_file,
    view_log,
    view_profile,
    view_profile_readonly,
    view_proposal,
    view_proposal_log,
    view_proposal_review,
    view_proposal_review_decision,
    view_review_history,
    withdraw_proposal_review,
)
from core.logic import view_completed_proposal_review

urlpatterns = [
    re_path(  # Core Site.
        r'^admin/',
        admin.site.urls
    ),
    re_path(
        r'^submission/',
        include(submission_urls)
    ),
    re_path(
        r'^manager/',
        include(manager_urls)
    ),
    re_path(
        r'^review/',
        include(review_urls)
    ),
    re_path(
        r'^api/',
        include(api_urls)
    ),
    re_path(
        r'^author/',
        include(author_urls)
    ),
    re_path(
        r'^editor/',
        include(editor_urls)
    ),
    re_path(
        r'^tasks/',
        include(onetasker_urls)
    ),
    re_path(
        r'^swiftsubmit/',
        include(swiftsubmit_urls)
    ),
    re_path(
        r'^editorialreview/',
        include(editorialreview_urls)
    ),
    re_path(  # 3rd Party Apps.
        r'^summernote/',
        include(django_summernote_urls)
    ),
    re_path(
        r'^accounts/',
        include(allauth_urls)
    ),
    re_path(
        r'^api-auth/',
        include(rest_framework_urls, namespace='rest_framework')
    ),
    re_path(  # Public pages.
        r'^$',
        index,
        name='index'
    ),
    re_path(
        r'^contact/$',
        contact,
        name='contact',
    ),
    re_path(
        r'^page/(?P<page_name>[-\w]+)/$',
        page,
        name='page',
    ),

    # Login/Register
    re_path(
        r'^login/$',
        login,
        name='login',
    ),
    re_path(
        r'^login/orcid/$',
        login_orcid,
        name='orcid-login',
    ),
    re_path(
        r'^logout/$',
        logout,
        name='logout',
    ),
    re_path(
         r'^switch/account/$',
         switch_account,
         name='switch-account',
    ),

    re_path(
        r'^switch/account/(?P<account_id>\d+)/$',
        switch_account_user,
        name='switch-account-user',
    ),
    re_path(
        r'^register/$',
        register,
        name='register',
    ),
    re_path(
        r'^login/activate/(?P<code>[-\w./]+)/$',
        activate,
        name='activate',
    ),
    re_path(  # Unauthenticated password reset.
        r'^login/reset/$',
        unauth_reset,
        name='unauth_reset',
    ),
    re_path(
        r'^login/reset/code/(?P<uuid>[\w-]+)/$',
        unauth_reset_code,
        name='unauth_reset_code',
    ),
    re_path(
        r'^login/reset/password/(?P<uuid>[\w-]+)/$',
        unauth_reset_password,
        name='unauth_reset_password',
    ),
    re_path(  # User profile.
        r'^user/profile/$',
        view_profile,
        name='view_profile',
    ),
    re_path(
        r'^user/view/(?P<user_id>\d+)/$',
        view_profile_readonly,
        name='view_profile_readonly',
    ),
    re_path(
        r'^user/review-history/(?P<user_id>\d+)/$',
        view_review_history,
        name='view_review_history',
    ),
    re_path(
        r'^user/profile/update/$',
        update_profile,
        name='update_profile',
    ),
    re_path(
        r'^user/profile/resetpassword/$',
        reset_password,
        name='reset_password',
    ),
    re_path(
        r'^user/task/new/$',
        task_new,
        name='task_new',
    ),
    re_path(
        r'^user/task/(?P<task_id>[-\w./]+)/complete/$',
        task_complete,
        name='task_complete',
    ),

    re_path(  # Message AJAX.
        r'^book/(?P<submission_id>\d+)/message/new/$',
        new_message,
        name='new_message',
    ),
    re_path(
        r'^book/(?P<submission_id>\d+)/messages/$',
        get_messages,
        name='get_messages',
    ),
    re_path(  # User submission.
        r'^user/submission/(?P<submission_id>\d+)/$',
        user_submission,
        name='user_submission',
    ),
    re_path(
        r'^user/proposal/(?P<proposal_id>\d+)/$',
        user_proposal,
        name='user_proposal',
    ),
    re_path(
        r'overview/$',
        overview,
        name='overview',
    ),
    re_path(
        r'overview/inprogress/$',
        overview_inprogress,
        name='overview_inprogress'
    ),
    re_path(
        r'overview/proposals/$',
        proposal_overview,
        name='proposal_overview',
    ),

    re_path(  # Email.
        r'^email/(?P<group>[-\w]+)/submission/(?P<submission_id>\d+)/$',
        email_users,
        name='email_users',
    ),
    re_path(
        r'^email/(?P<group>[-\w]+)/submission/(?P<submission_id>\d+)/'
        r'user/(?P<user_id>\d+)/$',
        email_users,
        name='email_user',
    ),
    re_path(
        r'^email/proposal/(?P<proposal_id>\d+)/user/(?P<user_id>\d+)/$',
        email_users_proposal,
        name='email_user_proposal',
    ),
     re_path(
        r'^email/primary-contact/$',
        email_primary_contact,
        name='email_primary_contact',
    ),
    re_path(
        r'^email/primary-contact/(?P<proposal_id>\d+)/$',
        email_primary_contact,
        name='email_primary_contact',
    ),

    re_path(
        r'^email/get/user/proposal/(?P<proposal_id>\d+)/$',
        get_proposal_users,
        name='get_proposal_users',
    ),
    re_path(
        r'^email/get/authors/submission/(?P<submission_id>\d+)/$',
        get_authors,
        name='get_authors',
    ),
    re_path(
        r'^email/get/editors/submission/(?P<submission_id>\d+)/$',
        get_editors,
        name='get_editors',
    ),
    re_path(
        r'^email/get/users/$',
        get_all_users,
        name='get_all_users',
    ),
    re_path(
        r'^email/get/onetaskers/submission/(?P<submission_id>\d+)/$',
        get_onetaskers,
        name='get_onetaskers',
    ),
    re_path(
        r'^email/get/all/submission/(?P<submission_id>\d+)/$',
        get_all,
        name='get_all',
    ),
    re_path(
        r'^email/general/$',
        email_general,
        name='email_general',
    ),
    re_path(
        r'^email/general/user/(?P<user_id>\d+)/$',
        email_general,
        name='email_general_user_id',
    ),
    re_path(  # Files.
        r'^files/submission/(?P<submission_id>\d+)/get/'
        r'marc21/(?P<type>[-\w]+)/$',
        serve_marc21_file,
        name='serve_marc21_file',
    ),
    re_path(
        r'^files/proposal/(?P<proposal_id>\d+)/file'
        r'/(?P<file_id>\d+)/download/$',
        serve_proposal_file_id,
        name='serve_proposal_file_id',
    ),

    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/file'
        r'/(?P<file_id>\d+)/download/review/(?P<review_id>\d+)'
        r'/access_key/(?P<access_key>[-\w+]+)/$',
        serve_file_one_click,
        name='serve_file_one_click'
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/file'
        r'/(?P<file_id>\d+)/download/$',
        serve_file,
        name='serve_file',
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/files/download/$',
        serve_all_files,
        name='serve_all_files',
    ),
    re_path(
        r'^files/user/email/file'
        r'/(?P<file_id>\d+)/download/$',
        serve_email_file,
        name='serve_email_file',
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/review-files/'
        r'(?P<review_type>[-\w]+)/download/review/(?P<review_id>\d+)/'
        r'access_key/(?P<access_key>[-\w+]+)/$',
        serve_all_review_files_one_click,
        name='serve_all_review_files_one_click',
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/review-files/'
        r'(?P<review_type>[-\w]+)/download/$',

src/editorialreview/urls.py
from django.urls import re_path

from .views import (
    add_editorial_review,
    download_editor_er_file,
    download_er_file,
    editorial_review,
    editorial_review_thanks,
    editorial_reviewer_email_editor,
    EditorialReviewCompletionEmail,
    email_editorial_review,
    remove_editorial_review,
    update_editorial_review_due_date,
    view_content_summary,
    view_editorial_review,
    view_non_editorial_review,
    withdraw_editorial_review,
)

urlpatterns = [
   re_path(
        r'(?P<submission_type>[-\w]+)/(?P<submission_id>\d+)/add/$',
        add_editorial_review,
        name='add_editorial_review'
   ),
   re_path(
        r'download/(?P<file_id>\d+)/review/(?P<review_id>\d+)/editor/$',
        download_editor_er_file,
        name='download_editor_er_file'
   ),
   re_path(
        r'download/(?P<file_id>\d+)/review/(?P<review_id>\d+)/$',
        download_er_file,
        name='download_er_file'
   ),
   re_path(
        r'editor/view/(?P<review_id>\d+)/$',
        view_editorial_review,
        name='view_editorial_review'
   ),
   re_path(
        r'remove/(?P<review_id>\d+)/$',
        remove_editorial_review,
        name='remove_editorial_review'
   ),
   re_path(
        r'withdraw/(?P<review_id>\d+)/$',
        withdraw_editorial_review,
        name='withdraw_editorial_review'
   ),
   re_path(
        r'update_due_date/(?P<review_id>\d+)/$',
        update_editorial_review_due_date,
        name='update_editorial_review_due_date'
   ),
   re_path(
        r'review/(?P<review_id>\d+)/view_review/'
        r'(?P<non_editorial_review_id>\d+)/$',
        view_non_editorial_review,
        name='view_non_editorial_review'
   ),
   re_path(
        r'review/(?P<review_id>\d+)/summary/$',
        view_content_summary,
        name='view_content_summary'
   ),
   re_path(
        r'review/(?P<review_id>\d+)/thanks/$',
        editorial_review_thanks,
        name='editorial_review_thanks'
   ),
   re_path(
        r'review/(?P<review_id>\d+)/completion_email/$',
        EditorialReviewCompletionEmail.as_view(),
        name='editorial_review_completion_email'
   ),
   re_path(
        r'review/(?P<review_id>\d+)/$',
        editorial_review,
        name='editorial_review'
   ),
   re_path(
        r'(?P<review_id>\d+)/email/$',
        email_editorial_review,
        name='email_editorial_review'
   ),
   re_path(
        r'(?P<review_id>\d+)/email/editor/$',
        editorial_reviewer_email_editor,
        name='editorial_reviewer_email_editor_not_logged_in'
   ),
   re_path(
        r'(?P<review_id>\d+)/email/editor/(?P<user_id>\d+)/$',
        editorial_reviewer_email_editor,
        name='editorial_reviewer_email_editor_logged_in'
   )
]

src/editorialreview/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.safestring import mark_safe


def review_recommendation():
    return (
        ('accept', 'Accept'),
        ('reject', 'Reject'),
        ('revisions', 'Revisions Required')
    )


class EditorialReview(models.Model):

    content_type = models.ForeignKey(
        ContentType,
        on_delete=models.CASCADE,
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey(
        'content_type',
        'object_id',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    assigning_editor = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name='editorial_review_assignments',
        on_delete=models.CASCADE,
    )
    assigned = models.DateField(
        auto_now_add=True,
    )
    due = models.DateField(
        blank=True,
        null=True,
    )
    completed = models.DateField(
        blank=True,
        null=True,
    )
    files = models.ManyToManyField(
        'core.File',
        blank=True,
        null=True,
    )
    body = models.TextField(
        blank=True,
        null=True,
    )
    access_key = models.CharField(
        max_length=200,
        null=True,
        blank=True,
    )
    results = models.ForeignKey(
        'review.FormResult',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )
    recommendation = models.CharField(
        max_length=10,
        choices=review_recommendation(),
        null=True,
        blank=True,
    )
    competing_interests = models.TextField(
        blank=True,
        null=True,
        help_text=mark_safe(
            "If any of the authors or editors have any competing interests "
            "please add them here. e.g.. "
            "'This study was paid for by corp xyz.'."
            " <a href='/page/competing_interests/'>More info</a>"
        )
    )
    # Used to ensure that an email is not sent more than once.
    overdue_reminder = models.BooleanField(
        default=False,
    )
    reopened = models.BooleanField(
        default=False,
    )
    withdrawn = models.BooleanField(
        default=False,
    )
    review_form = models.ForeignKey(
        'review.Form',
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return '{0} - {1} ({2})'.format(
            self.content_object.title.encode('utf8'),
            self.user.profile.full_name().encode('utf8'),
            self.content_type,
        )

    def is_overdue(self):
        return date.today() > self.due

src/editorialreview/forms.py
from django import forms

from editorialreview.models import EditorialReview


class EditorialReviewForm(forms.ModelForm):

    class Meta:
        model = EditorialReview
        fields = ('due',)

    def __init__(self, *args, **kwargs):
        super(EditorialReviewForm, self).__init__(*args, **kwargs)
        self.fields['due'].required = True


class RecommendationForm(forms.ModelForm):

    class Meta:
        model = EditorialReview
        fields = ("recommendation", "competing_interests")

    def __init__(self, *args, **kwargs):
        ci_required = kwargs.pop('ci_required', None)
        super(RecommendationForm, self).__init__(*args, **kwargs)

        if ci_required == 'on':
            self.fields['competing_interests'] = forms.CharField(
                widget=forms.Textarea,
                required=True,
            )
        self.fields['recommendation'].required = True

src/templates/editorialreview/add_editorial_review.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load bootstrap3 %}

{% block css %}
	<link href="{% static "css/timeline.css" %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css">
{% endblock %}

{% block body %}
<div class="col-md-12 file-heading  container-fluid" style="margin-top:-20px">
	<h3>Adding Editorial Review to {{ submission_type|capfirst }}: {{ submission.title }}
	{% if submission_type == 'proposal' %}
	<a href="{% url 'view_proposal' submission.id  %}" class="btn  btn-transparent-white" style="position: absolute;right:20;margin-top:-4px">Go back</a></h3>
	{% else %}
	<a href="{% url 'editor_submission' submission.id  %}" class="btn  btn-transparent-white" style="position: absolute;right:20;margin-top:-4px">Go back</a></h3>
	{% endif %}
</div>
	<br /><br />
	{% if check.status == False %}
		<div class="alert alert-danger">
		<ul>
		{% for k,v in check.iteritems %}
			{% if k == 'c_form' and v == False %}
			<li>You must set a due date</li>
			{% endif %}
			{% if k == 'c_reviewers' and v == False %}
			<li>You must select a reviewer</li>
			{% endif %}
			{% if k == 'c_review_form' and v == False %}
			<li>You must select a review form</li>
			{% endif %}
		{% endfor %}
		</ul>
		</div>
	{% endif %}
	<form method="POST">
	{% csrf_token %}
    <h4>1. Select Reviewers</h4>
	  <table class="table table-bordered small" cellspacing="0" width="100%" id='indv-reviewer'>
	    <thead>
	    <tr>
	      <th>First Name</th>
          <th>Last Name</th>
          <th>Group</th>
          <th>Email</th>
          <th>Profile</th>
          <th>Active Reviews</th>
          <th>Completed Reviews</th>
          <th>Declined Reviews</th>
          <th>Review History</th>
          <th>Select</th>
	    </tr>
	    </thead>
	    <tbody>
	    {% for reviewer in editorial_reviewers %}
            <tr>
              <td>{{ reviewer.user.first_name }}</td>
              <td>{{ reviewer.user.last_name }}</td>
              <td>
                  {% for group in editorial_groups %}
                    {% if group.id == reviewer.group_id %}
                        {{ group }}
                    {% endif %}
                  {% endfor %}
              </td>
              <td>{{ reviewer.user.email }}</td>
              <td><a href="{% url 'view_profile_readonly' reviewer.user.id %}" target="_blank">
                  {{ reviewer.user.first_name }} {{ reviewer.user.last_name }}</a></td>
              <td>{{ reviewer.user.profile.number_active_reviews }}</td>
              <td>{{ reviewer.user.profile.number_completed_reviews }}</td>
              <td>{{ reviewer.user.profile.number_declined_reviews }}</td>
              <td><a href="{% url 'view_review_history' reviewer.user.id %}" target="_blank">View</a></td>
              <td><input type="radio" name="reviewer" value="{{ reviewer.user.id }}"/></td>
            </tr>
	    {% endfor %}
		</tbody>
	  </table>
	<hr />

	<h4>2. Set due date</h4>
	{% bootstrap_field form.due %}
    <hr />

    <h4>3. Select Review Form</h4>
	    <p class="small">Select a review form for reviewers to complete.</p>
	        <select name="review_form" id="review_form" class="form-control">
                {% for form in review_forms %}
                    <option value="{{ form.ref }}" name="{{ form.ref }}">{{ form.name }}</option>
                {% endfor %}
	        </select>
    <hr />
	<p>On the next page you will have the option of drafting an email to your reviewer</p>
	<button type="submit" class="btn btn-primary pull-right">Submit</button>
    <br>
    <hr />
{% endblock body %}

{% block js %}
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.js"></script>
<script type="text/javascript">
    $(document).ready(function() {
    	$('#indv-reviewer').DataTable({
        	"lengthMenu": [[5,10,25], [5, 10, 25, 50, "All"]]
      	});
      	$('#id_due').datepicker({ dateFormat: 'yy-mm-dd' }).val();
   		});
</script>
{% endblock js %}

src/templates/editorialreview/editorial_review_thanks.html
{% extends "base.html" %}

{% block body %}
    <h3>Thank you for completing this review.</h3>
    <br>
    {% if request.user.is_authenticated %}
        <a href="{% url 'view_editorial_review' review.id %}?access_key={{ review.access_key }}">
            View your review
        </a>
        or
        <a href="{% url 'reviewer_dashboard' %}">
            return to reviewer dashboard.
        </a>
    {% else %}
        You can <a href="{% url 'login' %}">login</a> if you wish complete any further tasks.
    {% endif %}
{% endblock body %}

src/templates/editorialreview/submission_files.html
<h4>FILES</h4>
 <br>
<h5><b>Manuscript Files</b></h5>
<ul>
{% for file in submission.files.all %}
  {% if file.kind == 'manuscript' %}
    <li>
      <a href="{% url 'download_er_file' file.id review.id %}?access_key={{ review.access_key }}">
        <i class="fa fa-cloud-download">&nbsp;</i>Download {{ file.label }} ({{ file.original_filename }})
      </a>
    </li>
  {% endif %}
{% endfor %}
</ul>
<h5><b>Other Files</b></h5>
<ul>
{% for file in submission.files.all %}
  {% if file.kind != 'manuscript' %}
    <li>
      <a href="{% url 'download_er_file' file.id review.id %}?access_key={{ review.access_key }}">
        <i class="fa fa-cloud-download">&nbsp;</i>Download {{ file.label }} ({{ file.original_filename }})
      </a>
    </li>
  {% endif %}
{% endfor %}
</ul>
<br>

src/templates/editorialreview/view_editorial_review.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load bootstrap3 %}
{% load dict_lookup %}


{% block css %}
    <link href="{% static "css/timeline.css" %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css"
          href="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css">
{% endblock %}

{% block body %}
    <div class="col-md-12 file-heading  container-fluid"
         style="margin-top:-20px">
        <h3>Editorial Review for {{ review.content_object.title }}
            ({{ review.content_type|capfirst }})</h3>
        Viewing review by {{ review.user.profile.full_name }} - {{ review.id }}
        <br/><br/>
        <a class="btn btn-transparent-white"
           style="margin-bottom: 10px; margin-top: -10px;"
           href="#review-files">
            <i class="fa fa-arrow-down"></i>
            Jump to review files
        </a>
    </div>
    <br>
    <h4>Review: </h4>
    <div style="clear:both"></div>
    {% for item in data_ordered %}
        <div>
            <label>{{ item.0 }}</label>
            <p>{% lookup result.data item.0 %}</p>
        </div>
    {% endfor %}
    <br/><br/>
    <hr/>
    <h4>Recommendation: </h4>
    {{ review.get_recommendation_display }}
    <hr/>
    <h4>Competing Interests: </h4>
    {{ review.competing_interests|safe }}
    <br>
    If any of the authors or editors have any competing interests please add
    them here. e.g.. 'This study was paid for by corp xyz.'.
    <A href='/page/competing_interests/' target="_blank">More info</A>
    <br>
    <br>
    <hr/>
    <a name="review-files"></a>
    <h4>Review Files</h4>
    <ul>
        {% for file in review.files.all %}
            <li>
                <a href="{% url 'download_editor_er_file' file.id review.id %}?access_key={{ review.access_key }}">
                    {{ file.original_filename }}
                </a>
            </li>
        {% empty %}
            </ul>
            None
        {% endfor %}
    </ul>
    <br>
    <br>
    <hr>

{% endblock body %}

{% block js %}
    <script type="text/javascript">$("textarea").jqte();</script>
    <script type="text/javascript"
            src="{% static "js/fancyfile.js" %}"></script>
{% endblock js %}

src/templates/editorialreview/view_non_editorial_review.html
{% extends "base.html" %}
{% load static from staticfiles %}
{% load bootstrap3 %}
{% load dict_lookup %}


{% block css %}
	<link href="{% static "css/timeline.css" %}" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/plug-ins/1.10.7/integration/bootstrap/3/dataTables.bootstrap.css">
{% endblock %}

{% block body %}
<div class="col-md-12 file-heading  container-fluid" style="margin-top:-20px">
	<h3>Editorial Review for {{ review.content_object.title }} ({{ review.content_type|capfirst }})</h3>
	Viewing review by {{ peer_review.user.profile.full_name }} - {{ peer_review.id }}<br /><br />
</div>
	<br /><br />
	<h5>Review Files</h5>
	{% include "shared/review_files.html" with file_data=peer_review.files.all editorialreviewer=True %}
	<hr />
	<h4>Recommendation: </h4>
	{{ peer_review.get_recommendation_display }}
	<hr />
	<h4>Competing Interests: </h4>
	{{ peer_review.competing_interests|safe }}<br>If any of the authors or editors have any competing interests please add them here. e.g.. 'This study was paid for by corp xyz.'. <A href='/page/competing_interests/' target="_blank">More info</A></small><br><br>
	<hr />
	<h4>Review: </h4>
	<div style="clear:both"></div>
	{% for item in data_ordered %}
	<div>
	  <label>{{ item.0 }}</label>
	  <p>{% lookup result.data item.0 %} </p>
	</div>
	{% endfor %}


{% endblock body %}

{% block js %}
<script type="text/javascript">$("textarea").jqte();</script>
<script type="text/javascript" src="{% static "js/fancyfile.js" %}"></script>
{% endblock js %}