src/api/urls.py
from django.urls import (
    include,
    re_path,
)

from rest_framework import routers

from api.views import (
    index,
    JuraBookViewSet,
)

router = routers.DefaultRouter()
router.register(r'jura', JuraBookViewSet)

urlpatterns = [
    re_path(r'^$', index, name='index'),
    re_path(r'^', include(router.urls)),
]

src/author/urls.py
from django.urls import re_path

from .views import (
   author_contract_signoff,
   author_dashboard,
   author_production,
   author_submission,
   author_view_typesetter,
   copyedit_review,
   editing,
   proposal_author_contract_signoff,
   review,
   revise_file,
   revision,
   RevisionCompletionEmail,
   revision_new_file,
   status,
   tasks,
   typeset_review,
   view_chapter,
   view_chapter_format,
   view_copyedit,
   view_index,
   view_review_assignment,
   view_review_round,
   view_revisions,
)

urlpatterns = [
   re_path(
      r'dashboard/$',
      author_dashboard,
      name='author_dashboard'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/$',
      author_submission,
      name='author_submission'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/status/$',
      status,
      name='status'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/tasks/$',
      tasks,
      name='tasks'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/review/$',
      review,
      name='review'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/'
      r'review/revisions/(?P<revision_id>\d+)/$',
      view_revisions,
      name='view_revisions'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/'
      r'review/round/(?P<round_id>\d+)/$',
      view_review_round,
      name='view_review_round'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/'
      r'review/round/(?P<round_id>\d+)/assignment/(?P<review_id>\d+)/$',
      view_review_assignment,
      name='view_review_assignment'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/$',
      editing,
      name='editing'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'view/copyeditor/(?P<copyedit_id>\d+)/$',
      view_copyedit,
      name='author_view_copyedit'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'view/indexer/(?P<index_id>\d+)/$',
      view_index,
      name='author_view_index'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'copyedit/(?P<copyedit_id>\d+)/$',
      copyedit_review,
      name='copyedit_review'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/editing/'
      r'typeset/(?P<typeset_id>\d+)/$',
      typeset_review,
      name='typeset_review'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/$',
      author_production,
      name='author_production'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/'
      r'view/typesetter/(?P<typeset_id>\d+)$',
      author_view_typesetter,
      name='author_view_typesetter'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/$',
      revision,
      name='author_revision'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/completion_email/$',
      RevisionCompletionEmail.as_view(),
      name='author_revision_completion_email'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/update_file/(?P<file_id>\d+)/$',
      revise_file,
      name='revise_file'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/revisions/'
      r'(?P<revision_id>\d+)/new/(?P<file_type>[-\w]+)/file/$',
      revision_new_file,
      name='revision_new_file'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/contract/'
      r'(?P<contract_id>\d+)/signoff/$',
      author_contract_signoff,
      name='author_contract_signoff'
   ),
   re_path(
      r'^proposal/(?P<proposal_id>\d+)/contract/(?P<contract_id>\d+)/signoff/$',
      proposal_author_contract_signoff,
      name='proposal_author_contract_signoff'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/'
      r'chapter/(?P<chapter_id>\d+)/view/$',
      view_chapter,
      name='author_view_chapter'
   ),
   re_path(
      r'^submission/(?P<submission_id>\d+)/production/'
      r'chapter/(?P<chapter_id>\d+)/view/format/(?P<format_id>\d+)/$',
      view_chapter_format,
      name='author_view_chapter_format'
   ),
]

src/core/urls.py
from django.conf import settings
from django.urls import (
    include,
    re_path,
)
import django.views.static
from django.contrib import admin
from django.views.generic import TemplateView


import allauth.urls as allauth_urls
import rest_framework.urls as rest_framework_urls

import submission.urls as submission_urls
import manager.urls as manager_urls
import review.urls as review_urls
import api.urls as api_urls
import author.urls as author_urls
import editor.urls as editor_urls
import onetasker.urls as onetasker_urls
import swiftsubmit.urls as swiftsubmit_urls
import editorialreview.urls as editorialreview_urls
import django_summernote.urls as django_summernote_urls

from .views import (
    accept_proposal,
    activate,
    add_proposal_reviewers,
    assign_proposal,
    change_review_due_date,
    contact,
    contract_manager,
    dashboard,
    decline_proposal,
    delete_file,
    email_general,
    email_primary_contact,
    email_users,
    email_users_proposal,
    get_all,
    get_all_users,
    get_authors,
    get_editors,
    get_messages,
    get_onetaskers,
    get_proposal_users,
    index,
    login,
    login_orcid,
    logout,
    new_message,
    oai,
    overview,
    overview_inprogress,
    page,
    permission_denied,
    proposal,
    ProposalReviewCompletionEmail,
    proposal_add_editors,
    proposal_assign_edit,
    proposal_assign_user,
    proposal_assign_view,
    proposal_history,
    proposal_overview,
    proposal_review_declined,
    proposal_review_submitted,
    register,
    remove_proposal_review,
    reopen_proposal_review,
    RequestedReviewerDecisionEmail,
    request_proposal_revisions,
    reset_password,
    serve_all_files,
    serve_all_review_files,
    serve_all_review_files_one_click,
    serve_email_file,
    serve_file,
    serve_file_one_click,
    serve_marc21_file,
    serve_proposal_file_id,
    serve_versioned_file,
    start_proposal_review,
    switch_account,
    switch_account_user,
    task_complete,
    task_new,
    unauth_reset,
    unauth_reset_code,
    unauth_reset_password,
    update_file,
    update_profile,
    upload_additional,
    upload_manuscript,
    upload_misc_file,
    user_proposal,
    user_submission,
    versions_file,
    view_file,
    view_log,
    view_profile,
    view_profile_readonly,
    view_proposal,
    view_proposal_log,
    view_proposal_review,
    view_proposal_review_decision,
    view_review_history,
    withdraw_proposal_review,
)
from core.logic import view_completed_proposal_review

urlpatterns = [
    re_path(  # Core Site.
        r'^admin/',
        admin.site.urls
    ),
    re_path(
        r'^submission/',
        include(submission_urls)
    ),
    re_path(
        r'^manager/',
        include(manager_urls)
    ),
    re_path(
        r'^review/',
        include(review_urls)
    ),
    re_path(
        r'^api/',
        include(api_urls)
    ),
    re_path(
        r'^author/',
        include(author_urls)
    ),
    re_path(
        r'^editor/',
        include(editor_urls)
    ),
    re_path(
        r'^tasks/',
        include(onetasker_urls)
    ),
    re_path(
        r'^swiftsubmit/',
        include(swiftsubmit_urls)
    ),
    re_path(
        r'^editorialreview/',
        include(editorialreview_urls)
    ),
    re_path(  # 3rd Party Apps.
        r'^summernote/',
        include(django_summernote_urls)
    ),
    re_path(
        r'^accounts/',
        include(allauth_urls)
    ),
    re_path(
        r'^api-auth/',
        include(rest_framework_urls, namespace='rest_framework')
    ),
    re_path(  # Public pages.
        r'^$',
        index,
        name='index'
    ),
    re_path(
        r'^contact/$',
        contact,
        name='contact',
    ),
    re_path(
        r'^page/(?P<page_name>[-\w]+)/$',
        page,
        name='page',
    ),

    # Login/Register
    re_path(
        r'^login/$',
        login,
        name='login',
    ),
    re_path(
        r'^login/orcid/$',
        login_orcid,
        name='orcid-login',
    ),
    re_path(
        r'^logout/$',
        logout,
        name='logout',
    ),
    re_path(
         r'^switch/account/$',
         switch_account,
         name='switch-account',
    ),

    re_path(
        r'^switch/account/(?P<account_id>\d+)/$',
        switch_account_user,
        name='switch-account-user',
    ),
    re_path(
        r'^register/$',
        register,
        name='register',
    ),
    re_path(
        r'^login/activate/(?P<code>[-\w./]+)/$',
        activate,
        name='activate',
    ),
    re_path(  # Unauthenticated password reset.
        r'^login/reset/$',
        unauth_reset,
        name='unauth_reset',
    ),
    re_path(
        r'^login/reset/code/(?P<uuid>[\w-]+)/$',
        unauth_reset_code,
        name='unauth_reset_code',
    ),
    re_path(
        r'^login/reset/password/(?P<uuid>[\w-]+)/$',
        unauth_reset_password,
        name='unauth_reset_password',
    ),
    re_path(  # User profile.
        r'^user/profile/$',
        view_profile,
        name='view_profile',
    ),
    re_path(
        r'^user/view/(?P<user_id>\d+)/$',
        view_profile_readonly,
        name='view_profile_readonly',
    ),
    re_path(
        r'^user/review-history/(?P<user_id>\d+)/$',
        view_review_history,
        name='view_review_history',
    ),
    re_path(
        r'^user/profile/update/$',
        update_profile,
        name='update_profile',
    ),
    re_path(
        r'^user/profile/resetpassword/$',
        reset_password,
        name='reset_password',
    ),
    re_path(
        r'^user/task/new/$',
        task_new,
        name='task_new',
    ),
    re_path(
        r'^user/task/(?P<task_id>[-\w./]+)/complete/$',
        task_complete,
        name='task_complete',
    ),

    re_path(  # Message AJAX.
        r'^book/(?P<submission_id>\d+)/message/new/$',
        new_message,
        name='new_message',
    ),
    re_path(
        r'^book/(?P<submission_id>\d+)/messages/$',
        get_messages,
        name='get_messages',
    ),
    re_path(  # User submission.
        r'^user/submission/(?P<submission_id>\d+)/$',
        user_submission,
        name='user_submission',
    ),
    re_path(
        r'^user/proposal/(?P<proposal_id>\d+)/$',
        user_proposal,
        name='user_proposal',
    ),
    re_path(
        r'overview/$',
        overview,
        name='overview',
    ),
    re_path(
        r'overview/inprogress/$',
        overview_inprogress,
        name='overview_inprogress'
    ),
    re_path(
        r'overview/proposals/$',
        proposal_overview,
        name='proposal_overview',
    ),

    re_path(  # Email.
        r'^email/(?P<group>[-\w]+)/submission/(?P<submission_id>\d+)/$',
        email_users,
        name='email_users',
    ),
    re_path(
        r'^email/(?P<group>[-\w]+)/submission/(?P<submission_id>\d+)/'
        r'user/(?P<user_id>\d+)/$',
        email_users,
        name='email_user',
    ),
    re_path(
        r'^email/proposal/(?P<proposal_id>\d+)/user/(?P<user_id>\d+)/$',
        email_users_proposal,
        name='email_user_proposal',
    ),
     re_path(
        r'^email/primary-contact/$',
        email_primary_contact,
        name='email_primary_contact',
    ),
    re_path(
        r'^email/primary-contact/(?P<proposal_id>\d+)/$',
        email_primary_contact,
        name='email_primary_contact',
    ),

    re_path(
        r'^email/get/user/proposal/(?P<proposal_id>\d+)/$',
        get_proposal_users,
        name='get_proposal_users',
    ),
    re_path(
        r'^email/get/authors/submission/(?P<submission_id>\d+)/$',
        get_authors,
        name='get_authors',
    ),
    re_path(
        r'^email/get/editors/submission/(?P<submission_id>\d+)/$',
        get_editors,
        name='get_editors',
    ),
    re_path(
        r'^email/get/users/$',
        get_all_users,
        name='get_all_users',
    ),
    re_path(
        r'^email/get/onetaskers/submission/(?P<submission_id>\d+)/$',
        get_onetaskers,
        name='get_onetaskers',
    ),
    re_path(
        r'^email/get/all/submission/(?P<submission_id>\d+)/$',
        get_all,
        name='get_all',
    ),
    re_path(
        r'^email/general/$',
        email_general,
        name='email_general',
    ),
    re_path(
        r'^email/general/user/(?P<user_id>\d+)/$',
        email_general,
        name='email_general_user_id',
    ),
    re_path(  # Files.
        r'^files/submission/(?P<submission_id>\d+)/get/'
        r'marc21/(?P<type>[-\w]+)/$',
        serve_marc21_file,
        name='serve_marc21_file',
    ),
    re_path(
        r'^files/proposal/(?P<proposal_id>\d+)/file'
        r'/(?P<file_id>\d+)/download/$',
        serve_proposal_file_id,
        name='serve_proposal_file_id',
    ),

    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/file'
        r'/(?P<file_id>\d+)/download/review/(?P<review_id>\d+)'
        r'/access_key/(?P<access_key>[-\w+]+)/$',
        serve_file_one_click,
        name='serve_file_one_click'
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/file'
        r'/(?P<file_id>\d+)/download/$',
        serve_file,
        name='serve_file',
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/files/download/$',
        serve_all_files,
        name='serve_all_files',
    ),
    re_path(
        r'^files/user/email/file'
        r'/(?P<file_id>\d+)/download/$',
        serve_email_file,
        name='serve_email_file',
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/review-files/'
        r'(?P<review_type>[-\w]+)/download/review/(?P<review_id>\d+)/'
        r'access_key/(?P<access_key>[-\w+]+)/$',
        serve_all_review_files_one_click,
        name='serve_all_review_files_one_click',
    ),
    re_path(
        r'^files/user/submission/(?P<submission_id>\d+)/review-files/'
        r'(?P<review_type>[-\w]+)/download/$',

src/editor/models.py
from django.contrib.auth.models import User
from django.db import models


class CoverImageProof(models.Model):

    book = models.ForeignKey(
        'core.Book',
        on_delete=models.CASCADE,
    )
    editor = models.ForeignKey(
        User,
        verbose_name='editor',
        on_delete=models.CASCADE,
    )
    assigned = models.DateField(
        auto_now_add=True
    )
    note_to_author = models.TextField(
        help_text='Provide some notes on the cover for the author.'
    )
    completed = models.DateField(
        blank=True,
        null=True,
    )
    note_to_editor = models.TextField(
        help_text='Provide some feedback to the Editor on the cover image.'
    )

src/author/forms.py
from django import forms
from django.forms import ModelForm

from core import models as core_models
from editor import models as editor_models
from revisions import models as revision_models


class UploadContract(forms.ModelForm):

    class Meta:
        model = core_models.Contract
        exclude = ('author_file',)


class AuthorContractSignoff(forms.ModelForm):

    class Meta:
        model = core_models.Contract
        fields = ('author_file',)


class AuthorRevisionForm(ModelForm):

    class Meta:
        model = revision_models.Revision
        fields = ('cover_letter',)


class CoverImageReviewForm(forms.ModelForm):

    class Meta:
        model = editor_models.CoverImageProof
        fields = ('note_to_editor',)

src/templates/author/production/chapter_public_files.html
<ul class="media-list manuscript-upload-states">
  {% for file in chapter.formats.all %}
  <li class="media" style="background-color:rgb(230,230,230)">
    <div class="media-left">
      <span > <h1>
        {% if file.file.mime_type == 'image/jpeg' or file.file.mime_type == 'image/png' %}
       &nbsp; &nbsp;    <i class="fa fa-file-image-o"></i>
        {% else %}
        &nbsp; &nbsp;   <i class="fa fa-file-text-o"></i>
        {% endif %}
      </span></h1>
    </div>
    <div class="media-body">

        <div class="col-md-3">
          <h5><strong>{{ file.file.label }}</strong></h5>
          <h5><strong>{{ file.name }}</strong></h5>
          <h5>{{ file.file.original_filename|truncatechars:20 }}</h5>
        </div>
        <div class="col-md-3">
          <h5><strong>Identifier</strong></h5>
          <h5>{% if format_type == 'physical' %}--{% else %}{{ file.identifier }}{% endif %}</h5>
        </div>
        <div class="col-md-3">
          <h5><strong>File Type</strong></h5>
          <h5>{{ file.get_file_type_display }}</h5>
        </div>
        <div class="col-md-3">
          <h5><strong>Sequence</strong></h5>
          <h5>{{ file.sequence }}</h5>
        </div>
    </div>
    
    <div class="button-block-center">
      {% if not format_type == 'physical' %}
      <hr />
      <a href="{% url 'serve_file' submission.id file.file.id %}" class="btn btn-sm btn-task"><i class="fa fa-download">&nbsp;</i>Download</a>
      <td><a href="{% url 'update_format_or_chapter' submission.id 'chapter' file.id %}"  class="btn btn-sm btn-accept">&nbsp;<i class="fa fa-cloud-upload">&nbsp;</i>Update&nbsp;</a>
      <a target="_blank" href="{% url 'versions_file' submission.id file.file.id %}" class="btn btn-sm btn-view btn-round"><i class="fa fa-files-o">&nbsp;</i>Versions</a>
      <a href="{% url 'delete_file' submission.id file.file.id active %}" class="btn btn-sm btn-decline"><i class="fa fa-trash-o">&nbsp;</i>Delete</a>
      {% endif %}
    </div>
    </li>
    {% empty %}
     <li style="background-color:rgb(230,230,230)">
      <h5>&nbsp;&nbsp;&nbsp;No files</h5>
   </li>
  {% endfor %}
</ul>

src/templates/author/production/public_files.html
<ul class="media-list manuscript-upload-states">
  {% for file in format_data %}
  <li class="media" style="background-color:rgb(230,230,230)">
    <div class="media-left">
      <span > <h1>
        {% if file.file.mime_type == 'image/jpeg' or file.file.mime_type == 'image/png' %}
       &nbsp; &nbsp;    <i class="fa fa-file-image-o"></i>
        {% else %}
        &nbsp; &nbsp;   <i class="fa fa-file-text-o"></i>
        {% endif %}
      </span></h1>
    </div>
    <div class="media-body">

        <div class="col-md-4">
          <h5><strong>{{ file.name }}</strong></h5>
          <h5>{{ file.file.original_filename|truncatechars:20 }}</h5>
        </div>
        <div class="col-md-4">
          <h5><strong>Identifier</strong></h5>
          <h5>{{ file.identifier }}</h5>
        </div>
        <div class="col-md-4">
          <h5><strong>Sequence</strong></h5>
          <h5>{{ file.sequence }}</h5>
        </div>
    </div>
    <div class="button-block-center">
      <hr />
      <a href="{% url 'serve_file' submission.id file.file.id %}" class="btn btn-sm btn-task"><i class="fa fa-download">&nbsp;</i>Download</a>
      <a target="_blank" href="{% url 'versions_file' submission.id file.file.id %}" class="btn btn-sm btn-view btn-round"><i class="fa fa-files-o">&nbsp;</i>Versions</a>
    </div>
    </li>
    {% empty %}
     <li style="background-color:rgb(230,230,230)">
      <h5>&nbsp;&nbsp;&nbsp;No files</h5>
   </li>
  {% endfor %}
</ul>

src/templates/author/production/typesetting.html
{% if not submission.stage.typesetting %}
<p>Stage has not been initialised.</p>
{% else %}
<table class="table table-bordered">
	<tr>
		<th>Typeset Assignment</th>
		<th>Status</th>
		<th>View</th>
	</tr>
	{% for typeset in submission.typesetassignment_set.all %}
	{% ifequal typeset.id typeset_id %}
		<tr class="selected-row-table">
	{% else %}
		<tr>
	{% endifequal %}
		<td align="center">{{ typeset.id}}</td>
		<td><strong>{{ typeset.state.friendly }}</strong><br>{{ typeset.state.date }}</td>
		{% ifequal typeset.id typeset_id %}
			<td class="selected-row-table-arrow">
			{% else %}
			<td>
			{% endifequal %}<a href="{% url 'author_view_typesetter' submission.id typeset.id %}" class="btn  btn-task">View</a></td>
	</tr>
	{% empty %}
	<tr>
		<td colspan="3">No typesetters have been assigned</td>
	</tr>
	{% endfor %}
</table>
{% endif %}

src/templates/author/production/view.html
   <h4>Typesetting</h4>
  {% include "author/production/typesetting.html" %}

    <hr />
  <h4>Publication Formats</h4>
  {% include "author/production/public_files.html" with format_data=format_list format_type='format' %}
  <hr />
  <h4>Publication Chapters</h4>
<ul class="media-list manuscript-upload-states">
  {% for chapter in chapter_list %}
  <li class="media" style="background-color:rgb(230,230,230)">
    <div class="media-left">
      <span> <h2>
        &nbsp; &nbsp;   <i class="fa fa-file-text-o" style="padding-bottom:5px"></i> <strong style="font-size: 22px">Chapter {{ chapter.sequence }}</strong> 
      </span></h2>
    </div>
    <div class="media-body">

        <div class="col-md-12">
          <h4><a href="{% url 'author_view_chapter' submission.id chapter.id %}" class="btn btn-task pull-right" style="width:100px">View</a></h4>
        </div>
         
    </div>
    
    <div class="button-block-center">
     <hr />
     <div class="col-md-6">

            <strong>Blurb</strong>
          <h5><strong>{% if chapter.blurb %}{{ chapter.blurb }}{% else %}None.{% endif %}</strong></h5>
          </div>
     <div class="col-md-6">

           <div class="list-group">
            <strong>Formats</strong>
          {% for format in chapter.formats.all %}
            <a class="list-group-item" href='{% url 'author_view_chapter_format' submission.id chapter.id format.id %}'><span class="badge">{{format.file_type}}</span>{{format.name}}</a>
          {% endfor %}
          </div>
        </div>
    
    </div>
    </li>
    {% empty %}
     <li style="background-color:rgb(230,230,230)">
      <h5>&nbsp;&nbsp;&nbsp;No Chapters</h5>
   </li>
  {% endfor %}
</ul>
  <hr />
  <h4>Cover Image Review</h4>
  <table class="table table-bordered table-condensed">
    <tr>
      <th>Editor</th>
      <th>Requested</th>
      <th>Completed</th>
      <th></th>
    </tr>
    {% for proof in submission.coverimageproof_set.all %}
    <tr>
      <td>{{ proof.editor.profile.full_name }}</td>
      <td>{{ proof.assigned }}</td>
      <td>{% if proof.completed %}{{ proof.completed }}{% else %}Awaiting response from author{% endif %}</td>
      <td><a class="btn btn-success" data-toggle="modal" data-target="#{{ proof.id }}">View</a></td>
    </tr>
    {% empty %}
    <tr>
      <td colspan="4">No outstanding proof requests.</td>
    </tr>
    {% endfor %}
  </table>
  {% for proof in submission.coverimageproof_set.all %}
    {% include "shared/modals/author_cover_proof.html" %}
  {% endfor %}

src/templates/author/production/view_typeset.html
{% load bootstrap3 %}


  <h3>TYPESET ASSIGNMENT: {{ typeset.id }}</h3>

  <ul class="timeline-dash">
    <li>
      <p class="timeline-dash-date">{{ typeset.requested }}</p>
      <div class="timeline-content-dash-closed">
        <h5>Requested</h5>
      </div>
    </li>
    {% if typeset.accepted %}
    <li>
       <p class="timeline-dash-date">{{ typeset.accepted }}</p>
      <div class="timeline-content-dash-closed">
        <h5>Accepted</h5>
      </div>
    </li>
    {% endif %}
    {% if typeset.completed %}
    <li>
       <p class="timeline-dash-date">{{ typeset.completed }}</p>
      <div class="timeline-content-dash-closed">
        <h5>Initial Assigment Completed</h5>
      </div>
    </li>
    {% endif %}
    {% if typeset.editor_review %}
    <li>
       <p class="timeline-dash-date">{{ typeset.editor_review }}</p>
      <div class="timeline-content-dash-closed">
        <h5>Editor Review</h5>
      </div>
    </li>
    {% endif %}
    {% if typeset.author_completed %}
    <li>
       <p class="timeline-dash-date">{{ typeset.author_completed }}</p>
      <div class="timeline-content-dash-closed">
        <h5>Author Review</h5>
      </div>
    </li>
    {% endif %}
    {% if typeset.editor_second_review %}
    <li>
       <p class="timeline-dash-date">{{ typeset.editor_second_review }}</p>
      <div class="timeline-content-dash-closed">
        <h5>Editor Review</h5>
      </div>
    </li>
    {% endif %}
    {% if typeset.typesetter_completed %}
    <li>
       <p class="timeline-dash-date">{{ typeset.typesetter_completed }}</p>
      <div class="timeline-content-dash-closed">
        <h5>Assignment Completed</h5>
      </div>
    </li>
    {% endif %}
  </ul>
  <hr />
  <h4>Assigned Files</h4>
  {% include 'shared/review_files.html' with file_data=typeset.files.all %}

  <!-- Tab panes -->
    <hr />
      <h4>Initial Typesetter Assignment</h4>
      <h4>Typesetter Files</h4>
      {% include 'shared/review_files.html' with file_data=typeset.typeset_files.all %}
      {% if typeset.completed and not typeset.editor_review %}
      <form method="POST">
        {% csrf_token %}
        <br />
        <button class="btn btn-success" name="invite_author">Invite Author to Review Typesetting</button>
      </form>
      {% elif typeset.completed and typeset.editor_review and not typeset.author_invited %}
      <h4>Invite Author to Review</h4>
      <form method="POST">
        {% csrf_token %}
        {% bootstrap_form author_form %}
        <div class="form-group">
          <label class="control-label" for="id_note_to_author">Email to Author</label>
          <textarea class="form-control" cols="40" id="email_text" name="email_text" rows="10" title="">{{ email_text }}</textarea>
        </div>
        <button class="btn btn-success" name="send_invite_author" id="send_invite_author" type="submit">Send Request</button>
      </form>
      {% elif typeset.completed and typeset.editor_review and typeset.author_invited %}
      <hr />
      <h4>Author Files</h4>
      {% include 'shared/review_files.html' with file_data=typeset.author_files.all %}
      </table>
      {% endif %}
      {% if typeset.author_completed and not typeset.editor_second_review %}
      <form method="POST">
        {% csrf_token %}
        <br />
      </form>
     
      {% elif typeset.author_completed and typeset.editor_second_review and typeset.typesetter_invited %}
      <hr />
       <h4>Typesetter Final Revision</h4>
      <h5>Note from Typesetter</h5>
      {{ typeset.note_from_typesetter|linebreaks }}
      <h4>Typesetter Final Files</h4>
      {% include 'shared/review_files.html' with file_data=typeset.typesetter_files.all %}

{% endif %}
    </div>
  </div>

{% block js %}
<script>
$(function() {
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        localStorage.setItem('typesetting_tabs', $(this).attr('href'));
    });
    var lastTab = localStorage.getItem('typesetting_tabs');
    if (lastTab) {
        $('[href="' + lastTab + '"]').tab('show');
    }
});
</script>
{% endblock js %}